### ISSUE TITLE
Crashes upon loading

### ISSUE THREAD

**Issue by coolbho3k** [coolbho3k/wcbnplayer#4]
No info yet. Probably due to web API changing.

**Comment by coolbho3k** [comment]
Investigated further, crash is due to the stream no longer supplying artist, DJ, song metadata. I don't know what to do in this case.

D/WCBNStation( 7431): Metadata string wcbn-2015-04-01-0600-EDT
E/AndroidRuntime( 7431): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime( 7431): Process: org.wcbn.player, PID: 7431
E/AndroidRuntime( 7431): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 7431): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime( 7431): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 7431): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 7431): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 7431): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime( 7431): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 7431): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 7431): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 7431): Caused by: java.lang.IllegalStateException: No successful match so far
E/AndroidRuntime( 7431): 	at java.util.regex.Matcher.ensureMatch(Matcher.java:471)
E/AndroidRuntime( 7431): 	at java.util.regex.Matcher.end(Matcher.java:559)
E/AndroidRuntime( 7431): 	at java.util.regex.Matcher.end(Matcher.java:550)
E/AndroidRuntime( 7431): 	at org.wcbn.android.station.wcbn.WCBNStation.fixMetadata(WCBNStation.java:120)
E/AndroidRuntime( 7431): 	at org.wcbn.android.StreamService$MetadataUpdateTask.doInBackground(StreamService.java:400)
E/AndroidRuntime( 7431): 	at org.wcbn.android.StreamService$MetadataUpdateTask.doInBackground(StreamService.java:394)
E/AndroidRuntime( 7431): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime( 7431): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 7431): 	... 4 more
W/ActivityManager( 1222):   Force finishing activity 1 org.wcbn.player/org.wcbn.android.MainActivity

**Comment by coolbho3k** [comment]
This can probably be fixed by parsing the playlist instead.

**Comment by coolbho3k** [comment]
Fixed in change 17125d5b26016cbad5e440b545371dcda5287975
